// Keyword filters for broad RSS feeds. Keep these lists intentionally strict:
// broad feeds are useful only while they do not flood ingest with generic tech/news items.

export const RU_AI_KEYWORDS: string[] = [
  'искусственный интеллект',
  'нейросеть',
  'нейросети',
  'машинное обучение',
  'языковая модель',
  'генеративный',
  'chatgpt',
  'gpt',
  'llm',
  'ии ',
  ' ии',
  'яндекс gpt',
  'gigachat',
  'сбер ai',
  'claude',
  'gemini',
  'mistral',
  'нейронная сеть',
  'автоматизация',
  'компьютерное зрение',
]

export const RU_AI_STARTUP_KEYWORDS: string[] = [
  'искусственный интеллект',
  'нейросеть',
  'нейросети',
  'машинное обучение',
  'языковая модель',
  'генеративн',
  'chatgpt',
  'gpt',
  'llm',
  'openai',
  'anthropic',
  'mistral',
  'стартап',
  'раунд',
  'инвестиции',
  'привлек',
  'посевной',
  'seed',
  'series a',
  'series b',
  'оценк',
  'венчур',
]

export const EN_AI_STARTUP_KEYWORDS: string[] = [
  'artificial intelligence',
  'generative ai',
  'machine learning',
  'language model',
  'foundation model',
  'llm',
  'openai',
  'anthropic',
  'deepmind',
  'mistral',
  'cohere',
  'cursor',
  'perplexity',
  'startup',
  'funding',
  'raises',
  'valuation',
  'seed',
  'seed round',
  'series a',
  'series b',
  'series c',
]
