export const guideArticleStyles = {
  article: 'mx-auto max-w-6xl px-4 py-8 md:py-10 lg:py-12',
  breadcrumbs: 'mb-8 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-muted',
  header: 'mb-10 max-w-4xl',
  eyebrow: 'mb-3 text-[12px] font-semibold uppercase text-accent',
  title: 'font-serif text-[34px] font-extrabold leading-tight text-ink md:text-[48px]',
  heroLead: 'mt-5 max-w-3xl text-[18px] font-medium leading-relaxed text-hero-muted md:text-[20px]',
  meta: 'mt-5 flex flex-wrap gap-x-4 gap-y-2 text-sm text-muted',
  cover: 'mb-10 overflow-hidden rounded border border-line bg-surface',
  layout: 'grid gap-10 lg:grid-cols-[220px_minmax(0,760px)] lg:items-start lg:gap-14',
  content: 'min-w-0',
  h2: 'mb-4 mt-14 scroll-mt-36 font-serif text-[26px] font-bold leading-tight text-ink first:mt-0 md:text-[30px] lg:scroll-mt-28',
  h3: 'mb-3 mt-9 scroll-mt-36 text-[20px] font-semibold leading-snug text-ink lg:scroll-mt-28',
  paragraph: 'mb-5 text-[17px] leading-[1.75] text-ink',
  quote: 'my-8 border-l-4 border-accent bg-surface px-5 py-4 text-[17px] font-medium leading-relaxed text-ink',
  list: 'mb-7 ml-6 space-y-2 text-[17px] leading-relaxed text-ink',
  tableWrap: 'my-8 overflow-x-auto rounded border border-line',
  mediaFigure: 'my-8 overflow-hidden rounded border border-line bg-surface',
  separator: 'my-10 border-line',
  inlineCta: 'my-10 rounded border border-line bg-surface px-5 py-5 md:px-6',
  endSection: 'mt-14 border-t border-line pt-10',
  mobileToc: 'sticky top-14 z-40 -mx-4 mb-10 border-y border-line bg-base/95 px-4 py-3 backdrop-blur lg:hidden',
  desktopTocWrap: 'sticky top-[88px] max-h-[calc(100vh-7rem)] overflow-y-auto border-r border-line pr-7 pt-1',
  tocLabel: 'mb-3 font-serif text-[10px] font-semibold uppercase tracking-[0.2em] text-muted',
}
