from functools import lru_cache

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    app_env: str = Field(default="local", alias="APP_ENV")
    app_host: str = Field(default="0.0.0.0", alias="APP_HOST")
    app_port: int = Field(default=8000, alias="APP_PORT")
    database_url: str = Field(alias="DATABASE_URL")
    bot_token: str = Field(alias="BOT_TOKEN")
    bot_polling_enabled: bool = Field(default=False, alias="BOT_POLLING_ENABLED")
    site_leads_chat_id: int | None = Field(default=None, alias="SITE_LEADS_CHAT_ID")
    resend_api_key: str | None = Field(default=None, alias="RESEND_API_KEY")
    smtp_host: str | None = Field(default=None, alias="SMTP_HOST")
    smtp_port: int | None = Field(default=None, alias="SMTP_PORT")
    smtp_secure: bool = Field(default=False, alias="SMTP_SECURE")
    smtp_user: str | None = Field(default=None, alias="SMTP_USER")
    smtp_pass: str | None = Field(default=None, alias="SMTP_PASS")
    leads_email_to: str | None = Field(default=None, alias="LEADS_EMAIL_TO")
    leads_email_from: str | None = Field(default=None, alias="LEADS_EMAIL_FROM")
    leads_email_from_name: str | None = Field(default=None, alias="LEADS_EMAIL_FROM_NAME")
    openai_api_key: str | None = Field(default=None, alias="OPENAI_API_KEY")
    openai_summary_enabled: bool = Field(default=True, alias="OPENAI_SUMMARY_ENABLED")
    openai_summary_model: str = Field(default="gpt-5-mini", alias="OPENAI_SUMMARY_MODEL")
    openai_api_base: str = Field(default="https://api.openai.com/v1", alias="OPENAI_API_BASE")
    openai_summary_timeout_seconds: float = Field(default=20.0, alias="OPENAI_SUMMARY_TIMEOUT_SECONDS")
    default_timezone: str = Field(default="Europe/Moscow", alias="DEFAULT_TIMEZONE")
    ingestion_interval_minutes: int = Field(default=30, alias="INGESTION_INTERVAL_MINUTES")
    ingestion_scheduler_enabled: bool = Field(default=True, alias="INGESTION_SCHEDULER_ENABLED")
    ingestion_http_timeout_seconds: float = Field(default=10.0, alias="INGESTION_HTTP_TIMEOUT_SECONDS")
    rss_freshness_window_minutes: int = Field(default=30, alias="RSS_FRESHNESS_WINDOW_MINUTES")
    official_blog_freshness_window_minutes: int = Field(default=20, alias="OFFICIAL_BLOG_FRESHNESS_WINDOW_MINUTES")
    website_freshness_window_minutes: int = Field(default=90, alias="WEBSITE_FRESHNESS_WINDOW_MINUTES")
    process_events_interval_minutes: int = Field(default=15, alias="PROCESS_EVENTS_INTERVAL_MINUTES")
    raw_shortlist_max_age_hours: int = Field(default=336, alias="RAW_SHORTLIST_MAX_AGE_HOURS")
    raw_shortlist_min_title_length: int = Field(default=12, alias="RAW_SHORTLIST_MIN_TITLE_LENGTH")
    raw_shortlist_min_title_tokens: int = Field(default=3, alias="RAW_SHORTLIST_MIN_TITLE_TOKENS")
    raw_shortlist_min_text_length: int = Field(default=20, alias="RAW_SHORTLIST_MIN_TEXT_LENGTH")
    raw_shortlist_duplicate_recent_days: int = Field(default=14, alias="RAW_SHORTLIST_DUPLICATE_RECENT_DAYS")
    process_events_scheduler_enabled: bool = Field(default=True, alias="PROCESS_EVENTS_SCHEDULER_ENABLED")
    event_llm_shortlist_threshold: float = Field(default=58.0, alias="EVENT_LLM_SHORTLIST_THRESHOLD")
    event_llm_shortlist_secondary_threshold: float = Field(default=48.0, alias="EVENT_LLM_SHORTLIST_SECONDARY_THRESHOLD")
    daily_digest_hour: int = Field(default=9, alias="DAILY_DIGEST_HOUR")
    daily_digest_minute: int = Field(default=0, alias="DAILY_DIGEST_MINUTE")
    weekly_digest_weekday: str = Field(default="mon", alias="WEEKLY_DIGEST_WEEKDAY")
    weekly_digest_hour: int = Field(default=9, alias="WEEKLY_DIGEST_HOUR")
    weekly_digest_minute: int = Field(default=15, alias="WEEKLY_DIGEST_MINUTE")
    digest_send_delay_minutes: int = Field(default=5, alias="DIGEST_SEND_DELAY_MINUTES")
    scheduler_misfire_grace_seconds: int = Field(default=900, alias="SCHEDULER_MISFIRE_GRACE_SECONDS")
    telegram_daily_min_ranking_score: float = Field(default=58.0, alias="TELEGRAM_DAILY_MIN_RANKING_SCORE")
    telegram_daily_fallback_min_score: float = Field(default=45.0, alias="TELEGRAM_DAILY_FALLBACK_MIN_SCORE")
    telegram_daily_total_cap: int = Field(default=5, alias="TELEGRAM_DAILY_TOTAL_CAP")
    telegram_daily_weak_day_total_cap: int = Field(default=3, alias="TELEGRAM_DAILY_WEAK_DAY_TOTAL_CAP")
    telegram_models_services_cap: int = Field(default=2, alias="TELEGRAM_MODELS_SERVICES_CAP")
    telegram_tools_coding_cap: int = Field(default=2, alias="TELEGRAM_TOOLS_CODING_CAP")
    telegram_investments_market_cap: int = Field(default=2, alias="TELEGRAM_INVESTMENTS_MARKET_CAP")
    telegram_ai_russia_cap: int = Field(default=2, alias="TELEGRAM_AI_RUSSIA_CAP")
    russia_relevance_min_score: float = Field(default=0.58, alias="RUSSIA_RELEVANCE_MIN_SCORE")
    russia_section_min_ranking_score: float = Field(default=48.0, alias="RUSSIA_SECTION_MIN_RANKING_SCORE")
    russia_source_review_max_error_rate: float = Field(default=0.45, alias="RUSSIA_SOURCE_REVIEW_MAX_ERROR_RATE")
    russia_source_review_min_raw_items: int = Field(default=1, alias="RUSSIA_SOURCE_REVIEW_MIN_RAW_ITEMS")


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
